#!/usr/bin/env bash

sudo -i
mkdir -p /mnt/user/home && cd /mnt/user/home
git clone https://github.com/dionysus777-333/nixos-config

display=$(grep 'mkHost {' ./flake.nix | awk '{print $1}' | nl -w3 -s': ')
confn=$(echo "$display" | awk 'END {print NR}')
echo "Choose config between: (Press 1-${confn})"
echo "${display}"
read -p "Choice: " user_choice
while ! [[ $user_choice -ge 1 && $user_choice -le $confn ]]; do
  echo "Please try again."
  read -p "Choice: " user_choice
done

TOTAL_RAM=$(free -m | awk '/^Mem:/{print $2}')
lsblk -o NAME,LABEL,TYPE
echo 'Type the name of the drive you would like to install on. (the part after /dev/)'
echo 'THIS WILL ERASE THE DRIVE!'
read -p "Name: " driveN

