# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, arch, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" "mmc_block" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = 
    if (arch == "AMD") then [ "kvm-amd" ]
    else if (arch == "INT") then [ "kvm-intel" ]
    else [];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."root".device = "/dev/disk/by-partlabel/cryptroot";
  boot.initrd.luks.devices."swap" = {
    device = "/dev/disk/by-partlabel/cryptswap";
    preLVM = true;
    allowDiscards = true;
  };

  fileSystems."/" =
    { device = "/dev/mapper/root";
      fsType = "ext4";
    };

  
  fileSystems."/boot" =
    { device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

   swapDevices = [ 
     { 
     device = "/dev/mapper/swap";
     }
   ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
